name: srisaurus
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@main
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
